name: Build Jackbox Cheat Menu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Build bundle.js
        run: |
          npm run setup
          npm run build
      - name: Push To Github
      - run: |
          git config --global user.name 'hostedposted'
          git config --global user.email 'hostedposted@users.noreply.github.com'
          git commit -am "Build bundle.js"
          git push
